"use strict";

module.exports = [
  "World of Balance, World Map",
  "World of Ruin, World Map",
  "Serpent Trench, World Map",
  "“On that day…“",
  "Shadow's Dream 1",
  "Mog's Explanation",
  "Blackjack, Upper Deck (general use)",
  "Blackjack, Inside",
  "Blackjack, Back Room",
  "“Choose A Scenario”",
  "Blackjack, Upper Deck (IAF sequence)",
  "Falcon, Upper Deck",
  "Falcon, Inside",
  "Falcon, Roof, Landing on Kefka's Tower",
  "Chocobo Stable, Outside (WOB, forested)",
  "Chocobo Stable, Inside",
  "Chocobo Stable, Outside (WOR, forested)",
  "Falcon, Upper Deck",
  "Narshe, Northern Cliff, Intro",
  "Narshe, Town, Beginning (WOB)",
  "Narshe, Town (WOB)",
  "Narshe, North of Town, Beginning (WOB)",
  "Narshe, Snow Battlefield (WOB)",
  "Narshe, Northern Cliff (WOB)",
  "Narshe, Weapons Shop",
  "Narshe, Armor Shop",
  "Narshe, Item Shop",
  "Narshe, Relics Shop",
  "Narshe, Inn",
  "Narshe, Pub",
  "Narshe, Elder's House",
  "DUMMIED - Chocobo Stable",
  "Narshe, Outside (WOR)",
  "Narshe, Outside, North (WOR)",
  "Narshe, Outside, Battlefield (WOR)",
  "Narshe, Outside, Northern Cliff (WOR)",
  "Narshe, Mines Cart Rail Rooms (WOR)",
  "Narshe, Mines Battle Room (WOR)",
  "Narshe, Mines 1 (WOR)",
  "Narshe, Outside, North, Beginning",
  "Narshe, Mines 1, Beginning (WOB)",
  "Narshe, Mines 1 (WOB)",
  "Narshe, Mines Esper Room, Beginning (WOB)",
  "Narshe, Mines Esper Room, Empty (WOB)",
  "Narshe, Moogle's Room (WOR)",
  "DUMMIED",
  "DUMMIED",
  "DUMMIED",
  "Narshe, Mines 2, From Secret (WOB)",
  "Narshe, Mines Checkpoint (WOB)",
  "Narshe, Mines 2 (WOB)",
  "Narshe, Mines Battle Room (WOB)",
  "Narshe, Moogle's Room (WOB)",
  "Cave to Figaro Castle, Room 2",
  "Figaro Castle, Submerging",
  "Figaro Castle, Outside",
  "Figaro Desert, Kefka & Troops",
  "Figaro Castle, King's Bedroom",
  "Figaro Castle, Throne Room",
  "Figaro Castle, Inside",
  "Figaro Castle, Library",
  "Figaro Castle, Basement 1",
  "Figaro Castle, Basement 2",
  "Figaro Castle, Basement 3",
  "Figaro Castle, Engine Room",
  "Figaro Castle, Treasure Room",
  "Figaro Castle, Regal Crown Room",
  "Figaro Castle, Outside, Nighttime",
  "Cave to South Figaro (WOR)",
  "Cave to South Figaro, Rooms",
  "Cave to South Figaro (WOB)",
  "Cave to South Figaro, Entrance",
  "Cave to South Figaro, Room 2",
  "Cave to South Figaro, Room 1",
  "South Figaro, Outside (WOR)",
  "South Figaro, Outside (WOB)",
  "South Figaro, Inn/Relics",
  "South Figaro, Arsenal",
  "South Figaro, Pub",
  "DUMMIED",
  "South Figaro, Chocobo Stable",
  "South Figaro, Rich Man's House",
  "DUMMIED",
  "South Figaro, Basement 1",
  "South Figaro, Basement 1 Clock Room",
  "South Figaro, Item Shop",
  "South Figaro, Duncan's House",
  "South Figaro, Basement 1 Monster Room",
  "South Figaro, Basement 1 Save Point",
  "South Figaro, Basement 2",
  "Cave to Figaro Castle, Entrance (WOR)",
  "South Figaro, Dock (WOR)",
  "Cave to Figaro Castle, Room 1",
  "Sabin's House, Outside",
  "Sabin's House, Inside",
  "Mt.Kolts, Entrance",
  "Mt.Kolts, Outside",
  "Mt.Kolts, Outside Bridge",
  "Mt.Kolts, Outside Vargas Area",
  "DUMMIED",
  "Mt.Kolts, Cave",
  "Mt.Kolts, Exit",
  "Mt.Kolts, Cliffs",
  "Mt.Kolts, Cave Save Point",
  "Narshe, School",
  "Narshe, School, Adv. Battle Tactics",
  "Narshe, School, Battle TacticsNarshe, School, Environmental Science",
  "Returner's Hideout, Entrance",
  "Returner's Hideout, Inside",
  "Returner's Hideout, Rooms",
  "Returner's Hideout, Inn",
  "Tunnel to Lete River",
  "Lete River",
  "Lete River Cave",
  "Gau's Father's House, Outside",
  "Gau's Father's House, Inside",
  "Military Base Camp",
  "DUMMIED",
  "Military Base Camp 2",
  "Doma Castle, Outside (WOB)",
  "Doma Castle, Outside Poisoning (WOB)",
  "DUMMIED",
  "Doma Castle, Inside",
  "Doma Castle, Cyan's Room",
  "Cyan's Dream, Doma Castle, Outside",
  "Cyan's Dream, Doma Castle Rooms",
  "Duncan's House, Outside",
  "Duncan's House, Inside",
  "Ending, sky with birds",
  "Ending, Phantom Forest",
  "Gau's Father's House, Outside (WOR)",
  "Phantom Forest 1",
  "Phantom Forest 2",
  "Phantom Forest 3",
  "Phantom Forest 4",
  "Ending, mountain bridge",
  "Phantom Train, Docking Station 4",
  "Phantom Train, Docking Station 2",
  "Phantom Train, Docking Station 3",
  "Phantom Train, Docking Station 1",
  "Phantom Train, Outside 2",
  "Phantom Train, Outside 1",
  "Cyan's Dream, Phantom Train, Outside",
  "Cyan's Dream, Phantom Train, InsidePhantom Train, Inside 1",
  "Phantom Train, Engineer's Room",
  "Phantom Train, Restaurant",
  "Mobliz, Outside during Light of Judgement",
  "Phantom Train, Inside 2",
  "Mobliz, Basement 2, After Phunbaba 1",
  "Phantom Train, Inside 3",
  "Phantom Train, Inside 4",
  "Phantom Train, Inside Rooms",
  "Mobliz, Basement 2Waterfall Cave",
  "Waterfall Cliff",
  "Mobliz, Outside (WOB)",
  "Mobliz, Outside (WOR)",
  "Veldt Shore",
  "Mobliz, Inn",
  "Mobliz, Arsenal",
  "Mobliz, Relics",
  "Mobliz, Mail House",
  "Mobliz, Item Shop",
  "Mobliz, Basement 1",
  "Waterfall Entrance",
  "Veldt Cave to Waterfall",
  "Veldt Waterfall",
  "Nikeah, Outside",
  "Veldt Shore",
  "Nikeah, Inn",
  "Nikeah, Pub",
  "Nikeah, Chocobo Stable",
  "Shadow's Dream 2, Phantom Forest",
  "Serpent Trench Cave 1",
  "Mt.Zozo, Outside Bridge",
  "Mt.Zozo, Outside 1",
  "Mt.Zozo, Outside 2",
  "Mt.Zozo, Inside",
  "Mt.Zozo, Cyan's Room",
  "Mt.Zozo, Cliff",
  "Ending, Relm, Shadow, Strago",
  "Mobliz, Basement 2, Before Kefka Fight",
  "Mobliz, Outside, Before Kefka Fight",
  "Crazy Man's House, Outside",
  "Crazy Man's House, Inside",
  "Nikeah, Ferry (WOB)",
  "Kohlingen, Outside (WOB)",
  "Kohlingen, Outside (WOR)",
  "Ending, Rapids",
  "Kohlingen, Inn (WOR)",
  "DUMMIED - Kohlingen",
  "DUMMIED - Kohlingen, Arsenal",
  "Kohlingen, General Store",
  "Kohlingen, Chemist's House",
  "Maranda, Flower Girl's House (WOR)",
  "Kohlingen, Rachel's House",
  "Jidoor, Outside",
  "FREE TO USE",
  "Jidoor, Auction House",
  "Jidoor, Item Shop",
  "Jidoor, Relics",
  "Jidoor, Armor Shop",
  "Jidoor, Weapon Shop",
  "Jidoor, Chocobo Stable",
  "Jidoor, Inn",
  "Owzer's House, Basement",
  "Owzer's House, Art Room",
  "Owzer's House, F1",
  "Ending, Cyan 1",
  "Ending, Umaro, Mog 1",
  "Ending, Gogo 1",
  "Ending, Gau 1",
  "Cliff, Setzer waits for Darill",
  "Ending, Falcon flying through sky",
  "Esper World, Lake",
  "Esper World, Outside",
  "Esper World, Gate",
  "Esper World, House",
  "DUMMIED - boat dock",
  "Zozo, Outside",
  "FREE TO USE",
  "FREE TO USE",
  "FREE TO USE",
  "Zozo, Inside House",
  "Zozo, Terra's Room",
  "FREE TO USE",
  "FREE TO USE",
  "FREE TO USE",
  "FREE TO USE",
  "Opera House, Theater",
  "Opera House, Switch Room",
  "Opera House, Theater Play 2",
  "Opera House, Theater Play 1",
  "Opera House, Ceiling",
  "Opera House, Castle Balcony",
  "Opera House, Main",
  "Opera House, Dressing Room",
  "DUMMIED - Opera House",
  "Vector, after Magitek Factory",
  "Imperial Castle, Cranes Activating",
  "Vector, Outside",
  "Imperial Castle",
  "Imperial Castle, Outside Roof",
  "Vector, Inn",
  "Vector, Weapon Shop",
  "Vector, Pub",
  "Vector, Armor Shop",
  "Vector, Healer's House",
  "Imperial Castle, Inside",
  "Imperial Castle, Banquet",
  "Imperial Castle, Bedroom",
  "Vector, Outside, Burning",
  "Ending, Cyan, Mog, Gogo 2",
  "Ending, Setzer",
  "Ending, Umaro 2",
  "DUMMIED - Magitek Factory",
  "Ending, Edgar and Sabin",
  "Ending, Falcon taking flight from Kefka's Tower",
  "Ending, Locke and Celes 1",
  "Ending, Shadow, Strago, Gau 2",
  "Magitek Factory, Room 1",
  "Magitek Factory, Room 2",
  "Magitek Factory, Room 3 (Espers)",
  "DUMMIED - Magitek Factory",
  "Magitek Factory, Elevator",
  "DUMMIED - Magitek Factory",
  "Ending, Terra",
  "Magitek Factory, Room 4",
  "Magitek Factory, Room 5 (Save)",
  "Magitek Res. Facility, Room 1",
  "Magitek Factory, Minecart Dock",
  "Magitek Res. Facility, Room 2 (Number 042)",
  "Magitek Res. Facility, Espers",
  "DUMMIED",
  "Zone Eater's Stomach, Room 1",
  "Zone Eater's Stomach, Room 4",
  "Zone Eater's Stomach, Room 6 (Gogo)",
  "Zone Eater's Stomach, Room 2",
  "Zone Eater's Stomach, Room 3,5",
  "Narshe, Umaro's Cave 1",
  "Narshe, Umaro's Cave 2",
  "Narshe, Umaro's Lair",
  "Maranda, Outside (WOR)",
  "Doma Castle, Outside, Abandoned",
  "FREE TO USE",
  "Kefka's Tower, Inside From Guardian",
  "Maranda, Inn (WOR)",
  "Maranda, Weapon Shop (WOR)",
  "Maranda, Armor Shop (WOR)",
  "Kefka's Tower, Guardian's Room",
  "Kefka's Tower, Junk Room",
  "Kefka's Tower, Inside from Factory Room",
  "Kefka's Tower, Inside 2",
  "Kefka's Tower, Inside 3",
  "Kefka's Tower, Factory Room (Top Level)",
  "Darill's Tomb, Outside",
  "Darill's Tomb, Basement 1",
  "Darill's Tomb, Basement 2",
  "Darill's Tomb, Basement 3",
  "Darill's Tomb, Staircase",
  "Ending, Thamasa, Repairing burned house",
  "Kefka's Tower, Inside 1",
  "Kefka's Tower, Assassin Room",
  "Tzen, Outside (WOR)",
  "Tzen, Outside, Before House Collapse (WOR)",
  "Tzen, Item Shop (WOR)",
  "Tzen, Inn (WOR)",
  "Tzen, Weapon Shop (WOR)",
  "Tzen, Armor Shop (WOR)",
  "Tzen, Inside Collapsing House",
  "Tzen, Relics (WOR)",
  "Phoenix Cave, Big Lava Room, Drained",
  "Pheonix Cave, Big Lava Room",
  "Phoenix Cave, Main Room, Drained",
  "Phoenix Cave, Main Room",
  "Cyan's Dream, Three Stooges",
  "Pheonix Cave, Outside Entrance",
  "Cyan's Dream, Magitek Caves, Outside",
  "Cyan's Dream, Magitek Caves, Inside",
  "Cyan's Dream, Phantom Train, Inside 1",
  "Cyan's Dream, Phantom Train, Inside 2",
  "Albrook, Outside (WOB)",
  "Albrook, Outside (WOR)",
  "Albrook, Inn",
  "Albrook, Weapon Shop",
  "Albrook, Armor Shop",
  "Albrook, Item Shop",
  "Kefka's Tower, Room with Movers",
  "Albrook, Pub",
  "Kefka's Tower, Atma's Room",
  "Albrook, Ship Deck",
  "DUMMIED - Kefka's Tower, factory",
  "Kefka's Tower, Outside",
  "Kefka's Tower, Gold Dragon Room",
  "Kefka's Tower, Kefka's Lair 1",
  "Kefka's Tower, 4Ton Switch Room",
  "Kefka's Tower, Inside from Central Group",
  "Kefka's Tower, Inside from Eastern Group",
  "Thamasa, Outside, at Leo's Grave",
  "Thamasa, Outside, Kefka attacks",
  "DUMMIED - Thamasa",
  "Thamasa, Outside (WOB)",
  "Thamasa, Outside (WOR)",
  "Thamasa, Arsenal",
  "Thamasa, Inn",
  "Thamasa, Item Shop",
  "Thamasa, Elder's House",
  "Thamasa, Strago's House",
  "Thamasa, Relics",
  "Thamasa, Inside Burning House",
  "Kefka's Tower, Broken Capsules",
  "Cave in the Veldt (WOR)",
  "Kefka's Tower, Red Carpet Rooms",
  "Kefka's Tower, Three Switch Room",
  "Kefka's Tower, Left Statue Room",
  "Kefka's Tower, Kefka's Lair 2",
  "Floating Continent, Save Point",
  "Fanatic's Tower, Level 2",
  "Fanatic's Tower, Level 3",
  "Fanatic's Tower, Level 4",
  "Fanatic's Tower, Entrance",
  "Fanatic's Tower, Level 1",
  "Fanatic's Tower, Roof",
  "Fanatic's Tower, Treasure Room 2",
  "Fanatic's Tower, Gem Box Room",
  "Fanatic's Tower, Treasure Room 3",
  "Fanatic's Tower, Treasure Room 4",
  "Fanatic's Tower, Treasure Room 5",
  "Fanatic's Tower, Treasure Room 1",
  "Esper Cave, Statue Room",
  "Esper Cave, Outside 2",
  "Esper Cave, Outside 1",
  "Esper Cave, Outside 3",
  "Esper Cave",
  "Floating Continent, Destruction",
  "Imperial Base",
  "Imperial Base, House",
  "DUMMIED - Imperial Base",
  "Overhead View of World Map",
  "Mountains Destruction",
  "Cave to the Sealed Gate, Room 1",
  "Cave to the Sealed Gate, Basement 1",
  "Cave to the Sealed Gate, Basement 3",
  "Cave to the Sealed Gate, Basement 2",
  "Cave to the Sealed Gate, Save Point",
  "DUMMIED - Cave to the Sealed Gate, Basement 4",
  "DUMMIED - Cave to the Sealed Gate",
  "Grasslands Destruction",
  "Highlands Destruction",
  "Sealed Gate",
  "Floating Continent shadow cast above Jidoor",
  "Floating Continent, Breaking Apart",
  "Floating Continent, Outside",
  "Floating Continent Breakaway 1",
  "Cid's Island, Outside",
  "Cid's Island, Inside House",
  "Cid's Island, Beach",
  "Cid's Island, Cliff",
  "Cid's Island, Beach, no fish",
  "Ancient Cave 1",
  "Ancient Cave 2",
  "DUMMIED - Cid's Island, Beach",
  "Hidon's Cave",
  "Hidon's Cave, Entrance",
  "Ancient Castle, Inside",
  "Ancient Castle, Outside",
  "Ancient Castle, Eastern Room",
  "Kefka's Tower, Pipe Room",
  "Kefka's Tower, Factory Room (Bottom Level)",
  "Kefka's Tower, Final Room",
  "Kefka's Tower, Guardian Path Save Point",
  "Colosseum",
  "DUMMIED"
];
